"""
Convenience script to run some analytical-style queries on the transactional
data generated by the workload.
"""

from .db import db_cursor


def inventory_snapshot():
    print("=== Inventory snapshot ===")
    with db_cursor(dict_cursor=True) as cur:
        cur.execute(
            """
            SELECT
                p.product_id,
                p.product_name,
                p.category,
                i.stock
            FROM inventory i
            JOIN products p ON p.product_id = i.product_id
            ORDER BY p.product_id;
            """
        )
        for row in cur.fetchall():
            print(
                f"[{row['product_id']}] {row['product_name']} "
                f"({row['category']}): stock={row['stock']}"
            )


def top_customers(limit: int = 5):
    print(f"\n=== Top {limit} customers by spend ===")
    with db_cursor(dict_cursor=True) as cur:
        cur.execute(
            """
            SELECT 
                c.customer_id,
                c.first_name,
                c.last_name,
                COUNT(o.order_id) AS number_of_orders,
                SUM(p.price * o.quantity) AS total_spent
            FROM customers c
            JOIN orders o ON c.customer_id = o.customer_id
            JOIN products p ON o.product_id = p.product_id
            GROUP BY c.customer_id, c.first_name, c.last_name
            ORDER BY total_spent DESC
            LIMIT %s;
            """,
            (limit,),
        )
        for row in cur.fetchall():
            print(
                f"{row['customer_id']}: {row['first_name']} {row['last_name']} - "
                f"orders={row['number_of_orders']}, total_spent={row['total_spent']}"
            )


def sales_by_category():
    print("\n=== Sales by product category ===")
    with db_cursor(dict_cursor=True) as cur:
        cur.execute(
            """
            SELECT 
                p.category,
                SUM(o.quantity) AS items_sold,
                SUM(p.price * o.quantity) AS revenue
            FROM orders o
            JOIN products p ON o.product_id = p.product_id
            GROUP BY p.category
            ORDER BY revenue DESC;
            """
        )
        for row in cur.fetchall():
            print(
                f"{row['category']}: items_sold={row['items_sold']}, "
                f"revenue={row['revenue']}"
            )


def main():
    inventory_snapshot()
    top_customers(limit=5)
    sales_by_category()


if __name__ == "__main__":
    main()


